### ISSUE TITLE
Can't add network in docker container

### ISSUE THREAD

**Issue by shawnwang0715** [Synthetixio/synpress#224]
Sorry, I can't find a way to re-open the issue in https://github.com/Synthetixio/synpress/issues/215, so I create a new one.

When I try to add a network in docker container, it always gets stuck in here:
https://github.com/Synthetixio/synpress/blob/b9c2f3fdb7bb701fe190efe2099349e489d3d8e3/commands/metamask.js#L228-L230

Here's my `docker-compose.yml`:

```
services:
  synpress:
    image: synthetixio/docker-e2e:14.17-debian
    volumes:
      - './synpress:/home/app'
      - './synpress/node_modules:/home/node/app/node_modules'
    entrypoint: ["tail", "-f", "/dev/null"]
    environment:
      - SECRET_WORDS="test test test test test test test test test test test junk"
      - NETWORK_NAME="Smart Chain"
      - RPC_URL="https://bsc-dataseed.binance.org/"
      - CHAIN_ID="56"
      - SYMBOL="BNB"
      - BLOCK_EXPLORER="https://bscscan.com"
```

After starting the docker container, I run these commands:

```
npm i @synthetixio/synpress
npx synpress run --browser chrome --configFile 'tests/e2e/synpress.json'
```

My synpress.json has nothing special. I only changed the `baseUrl`

Then I always get 

```
     CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete.

Because this error occurred during a `before all` hook we are skipping all of the remaining tests.

Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail

```

Could you check whether adding network works in docker? Thanks!
