### ISSUE TITLE
Confirm Signature Request fails with timeout in GitHub Actions

### ISSUE THREAD

**Issue by rarecrumb** [Synthetixio/synpress#416]
I'm trying to run my tests inside of GitHub Actions on an ubuntu-latest runner.

When I get to `cy.confirmMetamaskSignatureRequest()`, the call just times out with:
```
cy.task('confirmMetamaskSignatureRequest') failed with the following error:

> waiting for function failed: timeout 30000ms exceeded

https://on.cypress.io/api/task
```

After reviewing the screen recording in cypress, I see that the metamask popup never shows up on top of the browser.

**Comment by pcardosolei** [comment]
did you manage to create the setup metamask?

**Comment by rarecrumb** [comment]
> you tried with retries?

Yes, currently making two attempts. It seems that the MetaMask popup is stuck behind the browser and Cypress won't switch over to it for some reason.

**Comment by pcardosolei** [comment]
I am using on github actions but i'm not using synpress as it is being used right now. i put synpress as a plugin directly in the cypress plugins so i can use it on the cypress open command to see what happens.

There is some stuff that can happen that is not intentional like changing file spec and the metamask wallet locks so that can be a reason.

**Comment by rarecrumb** [comment]
@pcardosolei can you share your GitHub Actions workflow? I'd like to see what else you're installing and how you're calling Cypress, installing the plugins, etc.

**Comment by pcardosolei** [comment]
```
name: CI - Test
on:
  pull_request:
    branches:
      - development

# cancelling jobs automatically.
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.5.0-chrome97-ff96
    env:
       VARIABLES RELATED WITH BUILD NOT RELEVANT TO HERE.
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: npm install
      - run: npm run build

      - name: "Tests - Chrome"
        uses: cypress-io/github-action@v2
        with:
          install: false
          headless: false
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          record: false
          parallel: false
          command: npm run cy:run
        env:
          CYPRESS_SECRET_WORDS: -
          CYPRESS_NETWORK_NAME: -
          CYPRESS_METAMASK_PW: -
          CYPRESS_SKIP_METAMASK_INSTALL: false
          CYPRESS_SKIP_METAMASK_SETUP: false
          CYPRESS_SKIP_RESOURCES_WAIT: true
          CYPRESS_REMOTE_DEBUGGING_PORT: 9222
```
