### ISSUE TITLE
synpress sometimes is unable to setup metamask because it starts on wrong window

### ISSUE THREAD

**Issue by roninjin10** [Synthetixio/synpress#493]
I am using Synpress to test https://app.optimism.io.   We run synpress with default synpress config in xvfb

On the very latest version of synpress, I notice the first tab is the metamask tab and the second tab is the cypress tab.    This is usually backwards.   And when this happens the focus on on the second tab and it fails to setup metamask. 

This happens on the second test suite when running locally and on all test suites on CI.  

This does not happen on any version before playwright was added.

Here is the github action we run to test our deployment at https://app.optimism.io

```
jobs:
  E2E_CANARY:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Synpress E2E Canary Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          # same as default synpress config but we set baseUrl to https://app.optimism.io
          run: synpress run --configFile synpress.js
        env:
          SECRET_WORDS: ${{ secrets.E2E_KOVAN_SEED }}
          CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/node_modules/.cache/Cypress
          CYPRESS_BASE_URL: https://app.optimism.io
          CYPRESS_RESOURCES_WAIT: 1

      - name: Archive e2e artifacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # pin@v2
        if: always()
        with:
          name: e2e-artifacts
          retention-days: 3
          path: |
            packages/frontend/tests/e2e/videos
            packages/frontend/tests/e2e/screenshots
        continue-on-error: true
```
