### ISSUE TITLE
`cy.task('acceptMetamaskAccess')` does not work in Codespaces

### ISSUE THREAD

**Issue by fionnachan** [Synthetixio/synpress#498]
Thanks for making `synpress`!

The same test works fine on my local machine (Windows) but failed within Codespaces.

```typescript
it("Should connect wallet using MetaMask successfully", () => {
  cy.visit(`/`);
  cy.findByText("Agree to terms").should("be.visible").click();
  cy.findByText("MetaMask").should("be.visible");
  cy.findByText("Connect to your MetaMask Wallet").click();
  cy.acceptMetamaskAccess().then(connected => {
    expect(connected).to.be.true;
    cy.switchToCypressWindow().should("be.true");
  });
});
```

```bash
  1 passing (48s)
  1 failing

  1) Login Account
       Should connect wallet using MetaMask successfully:
     CypressError: `cy.task('acceptMetamaskAccess')` failed with the following error:

> page.waitForNavigation: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
============================================================

https://on.cypress.io/api/task
      at http://localhost:3000/__cypress/runner/cypress_runner.js:145655:78
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:11318:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:9253:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:9310:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:9355:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:9431:18)
      at _drainQueueStep (http://localhost:3000/__cypress/runner/cypress_runner.js:6025:12)
      at _drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:6018:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:6034:5)
      at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:5904:14)
  From Your Spec Code:
      at Context.eval (http://localhost:3000/__cypress/tests?p=tests/support/index.js:487:13)
  
  From Node.js Internals:
    TimeoutError: page.waitForNavigation: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for navigation until "load"
    ============================================================
    page.waitForNavigation: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for navigation until "load"
    ============================================================
        at Object.waitAndClick (/workspaces/arb-token-bridge/node_modules/@synthetixio/synpress/commands/playwright.js:162:16)
        at Object.acceptAccess (/workspaces/arb-token-bridge/node_modules/@synthetixio/synpress/commands/metamask.js:591:5)
        at acceptMetamaskAccess (/workspaces/arb-token-bridge/node_modules/@synthetixio/synpress/plugins/index.js:183:24)
```

**Comment by drptbl** [comment]
Hey @fionnachan, thanks for report!

I will investigate this today.

Thanks,
Jakub.

**Comment by roninjin10** [comment]
I'm having same issue runing cypress in xvfb on 2.3.2

**Comment by drptbl** [comment]
@roninjin10 It also works locally but fails on Codespaces? Could you please upload a video from CI? Also, a sample failing e2e test would be very welcome :pray:.

**Comment by roninjin10** [comment]
No not using code spaces.  Unfortunately we are still in process of open sourcing the optimism gateway.  I might be able to ask to give you access though.

Here is a video.  I have a test run running with an infura key to see if that helps will update if that changes anything.
https://user-images.githubusercontent.com/35039927/190665127-1b571821-e0b8-498c-8ec4-aab68f285650.mp4

This is the github action I am running

The test file we are running is here https://gist.github.com/roninjin10/69ceae736d1f4122c37c8fe9199a6a0c

Version is synpress 2.3.2 

```
E2E:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Synpress E2E Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn e2e:ci
        env:
          SECRET_WORDS: ${{ secrets.E2E_KOVAN_SEED }}
          CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/node_modules/.cache/Cypress
          CYPRESS_RESOURCES_WAIT: 1

      - name: Archive e2e artifacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # pin@v2
        if: always()
        with:
          name: e2e-artifacts
          retention-days: 3
          path: |
            packages/frontend/tests/e2e/videos
            packages/frontend/tests/e2e/screenshots
        continue-on-error: true
```
