### ISSUE TITLE
MetaMask notifications not running on linux CircleCI

### ISSUE THREAD

**Issue by andreivcodes** [Synthetixio/synpress#590]
Hello,

I am trying to set up CI for our frontend using CircleCI but if I want to use a linux machine, cypress is not able to switch to notification windows for some reason.

If I switch the CircleCI config to a macos machine, everything works well.
I also tried the same setup locally on a macos and an ubuntu machine and both work fine.

Are there any working examples for synpress and CircleCI?

Every other E2E test is working as expected, so the cypress configuration is probably fine.

Thank you!

My CircleCI config 

```
version: 2.1
orbs:
  node: circleci/node@5.0.3
  browser-tools: circleci/browser-tools@1.4.0

commands:
  build-command:
    steps:
      - run:
          name: Build
          command: yarn build
          no_output_timeout: 30m

  test-command:
    steps:
      - run:
          name: Test
          command: yarn test:web
          no_output_timeout: 30m

  store-results-command:
    steps:
      - store_artifacts:
          path: /home/circleci/project/apps/web/tests/e2e/screenshots/
      - store_artifacts:
          path: /home/circleci/project/apps/web/tests/e2e/videos/

jobs:
  synpress-e2e-job:
    machine: # executor type
      image: ubuntu-2204:current
    steps:
      - checkout

      - browser-tools/install-browser-tools:
          replace-existing-chrome: true
          chrome-version: 108.0.5359.71

      - run:
          command: |
            google-chrome --version

      - node/install:
          install-yarn: true
          node-version: "18.12"

      - node/install-packages:
          pkg-manager: yarn

      - build-command
      - test-command
      - store-results-command

workflows:
  synpress-e2e:
    jobs:
      - synpress-e2e-job
```

Package.json

```
        "synpress": "synpress open --configFile=synpress.config.ts",
        "test:e2e": "synpress run --configFile=synpress.config.ts --browser chrome",
        "test": "start-server-and-test dev http://localhost:3000 test:e2e",
        "test:web": "start-server-and-test dev http://localhost:3000 test:e2e",
        "start": "next start",
        "start:web": "next start",
```

01_web3_login.cy.ts

```
describe('login', () => {
    beforeEach(() => {
        cy.visit('http://localhost:3000/dashboard/daos')
    })

    it('it should do wallet connect', () => {
        /* ==== Generated with Cypress Studio ==== */
        cy.contains('Connect Wallet').click()
        cy.contains('MetaMask').click()
        cy.acceptMetamaskAccess()
        cy.contains('Send message').click()
        cy.confirmMetamaskSignatureRequest()
        cy.get('[data-testid="rk-account-button"]').should(
            'have.text',
            '0 ETH🍣0xf3…2266'
        )
        /* ==== End Cypress Studio ==== */
    })

    it('it should do wallet connect again', () => {
        /* ==== Generated with Cypress Studio ==== */
        cy.contains('Connect Wallet').click()
        cy.contains('Send message').click()
        cy.confirmMetamaskSignatureRequest()
        cy.get('[data-testid="rk-account-button"]').should(
            'have.text',
            '0 ETH🍣0xf3…2266'
        )
        /* ==== End Cypress Studio ==== */
    })
})
```

And the error messages

```
@senate/web:test:web:   (Video)
@senate/web:test:web: 
@senate/web:test:web:   -  Started processing:  Compressing to 32 CRF                                                     
@senate/web:test:web:   -  Finished processing: /home/circleci/project/apps/web/tests/e2e/videos/01_layout/     (1 second)
@senate/web:test:web:                           02_dashboard/02_proposals/02_proposals-past.cy.ts.mp4                     
@senate/web:test:web: 
@senate/web:test:web: 
@senate/web:test:web: ────────────────────────────────────────────────────────────────────────────────────────────────────
@senate/web:test:web:                                                                                                     
@senate/web:test:web:   Running:  03_functional/01_web3_login.cy.ts                                               (7 of 9)
@senate/web:test:web: 
@senate/web:test:web: 
@senate/web:test:web:   login
@senate/web:test:web:     (Attempt 1 of 2) it should do wallet connect
@senate/web:test:web:     1) it should do wallet connect
@senate/web:test:web:     (Attempt 1 of 2) it should do wallet connect again
@senate/web:test:web:     2) it should do wallet connect again
@senate/web:test:web: 
@senate/web:test:web: 
@senate/web:test:web:   0 passing (2m)
@senate/web:test:web:   2 failing
@senate/web:test:web: 
@senate/web:test:web:   1) login
@senate/web:test:web:        it should do wallet connect:
@senate/web:test:web:      CypressError: `cy.task('acceptMetamaskAccess')` failed with the following error:
@senate/web:test:web: 
@senate/web:test:web: > page.waitForSelector: Timeout 30000ms exceeded.
@senate/web:test:web: =========================== logs ===========================
@senate/web:test:web: waiting for locator('.notification #app-content .app') to be visible
@senate/web:test:web:   locator resolved to hidden <div class="app os-linux">…</div>
@senate/web:test:web: ============================================================
@senate/web:test:web: 
@senate/web:test:web: https://on.cypress.io/api/task
@senate/web:test:web:       at <unknown> (*********************/__cypress/runner/cypress_runner.js:146171:78)
@senate/web:test:web:       at tryCatcher (*********************/__cypress/runner/cypress_runner.js:11327:23)
@senate/web:test:web:       at Promise._settlePromiseFromHandler (*********************/__cypress/runner/cypress_runner.js:9262:31)
@senate/web:test:web:       at Promise._settlePromise (*********************/__cypress/runner/cypress_runner.js:9319:18)
@senate/web:test:web:       at Promise._settlePromise0 (*********************/__cypress/runner/cypress_runner.js:9364:10)
@senate/web:test:web:       at Promise._settlePromises (*********************/__cypress/runner/cypress_runner.js:9440:18)
@senate/web:test:web:       at _drainQueueStep (*********************/__cypress/runner/cypress_runner.js:6034:12)
@senate/web:test:web:       at _drainQueue (*********************/__cypress/runner/cypress_runner.js:6027:9)
@senate/web:test:web:       at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (*********************/__cypress/runner/cypress_runner.js:6043:5)
@senate/web:test:web:       at Async.drainQueues (*********************/__cypress/runner/cypress_runner.js:5913:14)
@senate/web:test:web:   From Your Spec Code:
@senate/web:test:web:       at Context.eval (webpack:////home/circleci/project/node_modules/@synthetixio/synpress/support/commands.js:188:0)
@senate/web:test:web:   
@senate/web:test:web:   From Node.js Internals:
@senate/web:test:web:     TimeoutError: page.waitForSelector: Timeout 30000ms exceeded.
@senate/web:test:web:     =========================== logs ===========================
@senate/web:test:web:     waiting for locator('.notification #app-content .app') to be visible
@senate/web:test:web:       locator resolved to hidden <div class="app os-linux">…</div>
@senate/web:test:web:     ============================================================
@senate/web:test:web:     page.waitForSelector: Timeout 30000ms exceeded.
@senate/web:test:web:     =========================== logs ===========================
@senate/web:test:web:     waiting for locator('.notification #app-content .app') to be visible
@senate/web:test:web:       locator resolved to hidden <div class="app os-linux">…</div>
@senate/web:test:web:     ============================================================
@senate/web:test:web:         at Object.waitFor (/home/circleci/project/node_modules/@synthetixio/synpress/commands/playwright.js:143:16)
@senate/web:test:web:         at Object.switchToMetamaskNotification (/home/circleci/project/node_modules/@synthetixio/synpress/commands/playwright.js:123:9)
@senate/web:test:web:         at Object.acceptAccess (/home/circleci/project/node_modules/@synthetixio/synpress/commands/metamask.js:785:30)
@senate/web:test:web:         at acceptMetamaskAccess (/home/circleci/project/node_modules/@synthetixio/synpress/plugins/index.js:229:24)
@senate/web:test:web: 
@senate/web:test:web:   2) login
@senate/web:test:web:        it should do wallet connect again:
@senate/web:test:web:      AssertionError: Timed out retrying after 10000ms: Expected to find content: 'Send message' but never did.
@senate/web:test:web:       at Context.eval (webpack:///./tests/e2e/specs/03_functional/01_web3_login.cy.ts:25:11)
@senate/web:test:web: 
@senate/web:test:web: 
@senate/web:test:web: 
@senate/web:test:web: 
@senate/web:test:web:   (Results)
```
